### ISSUE TITLE
Any ID that doesn't conform to the correct json output skips all 250 entries

### ISSUE THREAD

**Issue by PegasusPrime** [SteamDBAPI/db-builder#1]
In the example below, the 208140 is valid but is skipped since one of the 250 items is bad

Example: Error requesting data for the following ids: 208140, 208151, 208152, 208153, 208154, 208155, 208156, 208157, 208158, 208159, 208200, 208220, 208280, 208281, 208282, 208283, 208284, 208285, 208286, 208287, 208288, 208289, 208290, 208292, 208293, 208294, 208295, 208296, 208298, 208299, 208300, 208301, 208302, 208303, 208304, 208305, 208306, 208307, 208311, 208312, 208313, 208314, 208315, 208316, 208317, 208318, 208319, 208320, 208340, 208341, 208342, 208343, 208344, 208345, 208346, 208347, 208348, 208349, 208350, 208351, 208352, 208353, 208354, 208355, 208356, 208357, 208358, 208359, 208361, 208362, 208363, 208364, 208365, 208366, 208367, 208368, 208369, 208370, 208371, 208372, 208373, 208374, 208375, 208376, 208377, 208378, 208379, 208400, 208460, 208462, 208470, 208480, 208482, 208483, 208484, 208485, 208487, 208488, 208489, 208491, 208492, 208500, 208520, 208539, 208540, 208541, 208542, 208543, 208544, 208545, 208546, 208570, 208575, 208580, 208600, 208610, 208620, 208630, 208640, 208650, 208670, 208690, 208710, 208730, 208740, 208741, 208742, 208750, 208790, 208791, 208792, 208793, 208795, 208796, 208797, 208798, 208799, 208800, 208801, 208802, 208803, 208804, 208805, 208806, 208807, 208808, 208809, 208810, 208811, 208812, 208813, 208814, 208816, 208817, 208818, 208830, 208831, 208832, 208833, 208834, 208835, 208836, 208837, 208838, 208839, 208840, 208841, 208842, 208843, 208844, 208860, 208881, 208911, 208981, 208982, 208983, 208984, 208985, 209000, 209040, 209060, 209080, 209100, 209120, 209160, 209170, 209190, 209201, 209202, 209230, 209270, 209300, 209301, 209302, 209303, 209304, 209305, 209306, 209307, 209308, 209309, 209310, 209330, 209340, 209343, 209360, 209362, 209370, 209373, 209375, 209390, 209421, 209422, 209423, 209424, 209425, 209426, 209427, 209428, 209460, 209520, 209540, 209545, 209546, 209547, 209548, 209610, 209630, 209650, 209660, 209670, 209690, 209710, 209720, 209721, 209730, 209750, 209771, 209772, 209790, 209793, 209801, 209811, 209812, 209817, 209819, 209830, 209850, 209870, 209872
 continuing.

This works: http://store.steampowered.com/api/appdetails?appids=208140&filters=price_overview

**Comment by edwardslabs** [comment]
After looking into this further it appears that the issue is the length of the return that causes the request to return null. Now that blacklisted appids are removed from the master list it appears that every request of 250 appids returns null and every request needs to be split into smaller chunks.
