### ISSUE TITLE
During the initial DB creation no value is entered into last_update, highest_price, lowest_price.

### ISSUE THREAD

**Issue by edwardslabs** [SteamDBAPI/db-builder#3]
These values should be populated during the first run of fetcher.py and the initialization of an appid into the database.

**Comment by PegasusPrime** [comment]
The last_update defaults to NULL I believe until the second update which calls the timestamp on update function. The default for the high/lowest is 0 according to the Game object. I'll check the DB side

**Comment by edwardslabs** [comment]
On initialization shouldn't the highest_price and lowest_price have non-zero values and the last update should be the timestamp it was first entered?

**Comment by PegasusPrime** [comment]
Fixed in b76e2753e1f2bd7d3003cb2d471602f429c38ac0
