### ISSUE TITLE
Function to refresh the blacklist

### ISSUE THREAD

**Issue by PegasusPrime** [SteamDBAPI/db-builder#7]
There needs to be a function to re-check the blacklist from time to time. Example, I checked a game this morning, id 298360. The game wasn't in the database but was in the blacklist. Re-checking the steam url today shows it is valid json indicating that before it wasn't.

**Comment by edwardslabs** [comment]
http://store.steampowered.com/api/appdetails/?appids=583,440,730,298360&filters=price_overview

If you notice appid 583 returns success:false and 440 (tf2 which is free to play) returns success:true and data[] is empty. I wonder if we should extend the schema of blacklist to be able to decipher how the two fail, or possibly only add games where no price data is available and success:true.

**Comment by PegasusPrime** [comment]
Yeah that would probably be a good idea. Are all the f2p games in that format of sucess:true and data[]? I spot checked 5 or so f2p games and they all have that format

**Comment by PegasusPrime** [comment]
It looks like data[] could be a f2p game, a demo, a game "tool", game trailer so far

**Comment by PegasusPrime** [comment]
sqlite> select count(_) from blacklist;
3710
sqlite> select count(_) from games;
11143

**Comment by edwardslabs** [comment]
Interesting. It added a ton more games.
